name: sentry_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sentry_flutter: ^9.9.2
  flutter_riverpod: ^2.5.1
  go_router: ^17.0.1
  riverpod_annotation: ^2.3.5

  dio: ^5.5.0
  uuid: ^4.4.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.0.0

  cupertino_icons: ^1.0.8
  google_fonts: ^7.0.0
  google_maps_flutter: ^2.6.0
  image_picker: ^1.1.2

  permission_handler: ^12.0.1
  intl: ^0.20.2
  dartz: ^0.10.1
  equatable: ^2.0.8
  flutter_dotenv: ^6.0.0
  gal: ^2.3.2
  geolocator: ^14.0.2
  workmanager: ^0.9.0+3

  json_annotation: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
